"Lista de comandos de la terminal:"

"La terminal es sensible a las mayusculas"

pwd = "print work directory(imprime la direccion de carpeta)"
ls = "list(imprime la lista de archivos en carpeta)"
la -a = "permite ver carpetas ocultas"
mkdir = "make directory(crea una carpeta vacia a partir de un nombre que le damos)"
cd = "permite avanzar o retroceder dentro de la carpeta hacia otra carpeta. Ej: (cd ..) va hacia atras, mientras que (cd 'nombre de carpeta') va hacia esa carpeta"
clear = "limpia la terminal"
touch = "crea un archivo vacio(siempre hay que poner el nombre del nuevo archivo que estamos creando junto con su extencion)"
rm = "remove(elimina el archivo indicado, siempre poniendo nombre de archivo con su extencion)"
rm -r = "elimina una carpeta indicando su nombre"
git init = "Crea la carpeta en la que estamos en repositorio"
git add 'nombre de archivo' = "agrega archivo individual al repositorio para luego guardarlo en la nube"
git add . = "agrega todos los archivos de la carpeta del repositorio para subirlos a la nube"
git commit -m "texto descriptivo del commit" = "Sube los archivos del repositorio a la nube con un mensaje sobre los cambios"
git log = "sirve para checkear el ultimo estado del commit"
git push = "comando para mandar nuestros commits a un servidor remoto"
git status = "ofrece una descripción del estado de los archivos"
git pull = "sirve para recibir cambios de repositorio remoto a local"